### ISSUE TITLE
Vue 3 compatible?

### ISSUE THREAD

**Issue by RaymondAtivie** [yoychen/v-craft#18]
Is this still under maintenance and is it compatible with vue 3?

**Comment by yoychen** [comment]
Sorry, because of some breaking change of Vue API and third-party packages is not compatible with Vue 3 currently. v-craft may not be compatible with Vue 3.

**Comment by DevPlus31** [comment]
Any updates?

**Comment by Milanator** [comment]
Is there any updates?
